### ISSUE TITLE
Can't decode enum tuple variants?

### ISSUE THREAD

**Issue by imsnif** [tailhook/knuffel#11]
Maybe I'm doing something wrong, but trying to do this:

```rust
use knuffel;

#[derive(knuffel::Decode)]
pub enum MyEnum {
    MyFirstVariant,
    VariantWithTuple(u8),
}

fn main() {
    println!("Hello, world!");
}
```

I get:
```
$ cargo check

error[E0277]: the trait bound `u8: Decode<S>` is not satisfied
 --> src/main.rs:3:10
  |
3 | #[derive(knuffel::Decode)]
  |          ^^^^^^^^^^^^^^^ the trait `Decode<S>` is not implemented for `u8`
  |
  = help: the following other types implement trait `Decode<S>`:
            Arc<T>
            Box<T>
            MyEnum
            Node<T>
            Rc<T>
            Spanned<Node<T>, T>
  = note: this error originates in the derive macro `knuffel::Decode` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Any clues?

**Comment by imsnif** [comment]
This works though:
```rust
#[derive(knuffel::Decode)]
pub struct MyStruct {
    foo: u8,
}
```

**Comment by rnarkk** [comment]
1. You want to add `#[knuffel(/* attribute */)]` attribute before `u8` depending on how you regard the value. See [Enum](https://docs.rs/knuffel/latest/knuffel/derive.Decode.html#enums).
2. If `A` implements `Decode` then `Variant(A)` works. See [Overview.2](https://docs.rs/knuffel/latest/knuffel/derive.Decode.html#:~:text=A%20single%2Dfield%20new%20type%20wrapper%20around%20such%20structure%20Wrapper(Inner)%20where%20Inner%20implements%20Decode%20(this%20is%20a%20tuple%20struct%20with%20single%20argument%20without%20annotations).).
3. The field `foo: u8` in your struct example isn't actually participating in decoding your document, and its value is being simply filled by `u8`'s `Default` value `0` due to the lack of an attribute `#[knuffel(/* attribute */)]` . See [Overview](https://docs.rs/knuffel/latest/knuffel/derive.Decode.html#:~:text=Unlike%20in%20serde%20and%20similar%20projects%2C%20non%2Dannotated%20fields%20are%20not%20decoded%20from%20source%20and%20are%20filled%20with%20std%3A%3Adefault%3A%3ADefault.).

**Comment by imsnif** [comment]
Hey, thanks for your response! I no longer have context on this since we ended up going with another solution.
