### ISSUE TITLE
`#[knuffel(child)] field: Option<T>`

### ISSUE THREAD

**Issue by rnarkk** [tailhook/knuffel#16]
Just like `#[knuffel(child)] field: bool` maps the presence/absence of `field` to `true`/`false`,
I expect `#[knuffel(child)] field: Option<T>` for `T` with`Decode` (without `Decode`) to map the presence/absence of `field { ..t }` (`field t`) to `Some(t)`/`None` where `t` : `T`.

Currently we get this error in some cases:

`error[E0277]: the trait bound std::option::Option<T>: Decode<S> is not satisfied`.

| field modes of `T` | `Option<T>` |
| - | - |
| all fields are `property` | DOESN’T WORK |
| all fields are `children` | WORKS |

**Comment by tailhook** [comment]
```rust
#[derive(Debug, knuffel::Decode)]
struct SomeDocument {
    #[knuffel(child)]
    field: Option<Node>,
}

#[derive(Debug, knuffel::Decode)]
struct Node {
}

```
Works for me, by yielding:
```
SomeDocument {
    field: None,
}
```
On an empty document and:
```
SomeDocument {
    field: Some(
        Node,
    ),
}
```
On document `field`.

The core thing here is that we don't implement `Decode` or `Option`, I think because of orphan rules (but I'm not sure, long time I didn't try that). But we use syntatic `Option<x>` in derive to find out this thing. So `std::option::Option<T>` or something like that doesn't work.

Or do you mean it doesn't work on generics?

**Comment by myrkvi** [comment]
I'm having the same issue with this:
```rust
#[derive(knuffel::Decode)]
struct Entry {
    #[knuffel(children(name="command"))]
    pub commands: Vec<Command>,
}

#[derive(knuffel::Decode)]
struct Command {
    #[knuffel(argument)]
    pub name: String,
    #[knuffel(child)]
    pub description: Option<String>,
}
```

Sample KDL:
```kdl
command "my-command" {
    description "A description for my command"
}
```

**Comment by tailhook** [comment]
Yes, childs can't be scalars without unwrap. If you have any ideas of where add some hint to the doc where it's visible for new users, feel free to post a PR.

I don't think we can improve the the error reporting, though. Because we only know that `String` is `std::str::String` on typecheck (after macro expansion). We could add a warning on some of the names that are typically scalars, like String, but warnings only work on nightly Rust. So let's wait until they stabilize.
