### ISSUE TITLE
Inconsistency of syntactical sites to become node names between nodes and their child nodes

### ISSUE THREAD

**Issue by rnarkk** [tailhook/knuffel#18]
As we can see below,

- whether nodes have arguments, properties or doesn't have one at all,
- whether they are modelled by tuple structs, struct structs or unit structs,

knuffel's mantra in mapping KDL to Rust should be simple: _a node's name is a struct's name or an enum's variant name_:

<table>
  <tr>
    <td>
      <pre lang="kdl"><code>node0</code></pre>
    </td>
    <td>
      <pre lang="kdl"><code>node1 1 "hoge"</code></pre>
    </td>
    <td>
      <pre lang="kdl"><code>node2 a=1 b="hoge"</code></pre>
    </td>
  </tr>
  <tr>
    <td colspan=3><i>structs</i></td> 
  </tr>
  <tr>
    <td rowspan=2>
      <pre>#[derive(Decode)]
struct Node0;</pre>
    </td>
    <td>
      <pre>#[derive(Decode)]
struct Node1(
    #[knuffel(argument)] i32,
    #[knuffel(argument)] String
);</pre>
    </td>
    <td>
      <pre>#[derive(Decode)]
struct Node2(
    #[knuffel(property(name = "a"))] i32,
    #[knuffel(property(name = "b"))] String
);</pre>
    </td>
  </tr>
  <tr>
    <td>
      <pre>#[derive(Decode)]
struct Node1 {
    #[knuffel(argument)] a: i32,
    #[knuffel(argument)] b: String
}</pre>
    </td>
    <td>
      <pre>#[derive(Decode)]
struct Node2 {
    #[knuffel(property)] a: i32,
    #[knuffel(property)] b: String
}</pre>
    </td>
  </tr>
  <tr>
    <td colspan=3><i>enums</i></td> 
  </tr>
  <tr>
    <td colspan=3>
      <pre>                          #[derive(Decode)]
                            enum Node {
                                Node0,
                                Node1(
                                    #[knuffel(argument)] i32,
                                    #[knuffel(argument)] String
                                ),
                                Node2(
                                    #[knuffel(property(name = "a"))] i32,
                                    #[knuffel(property(name = "b"))] String
                                )
                            }</pre>
    </td>
  </tr>
  <tr>
    <td colspan=3>
      <pre>                          #[derive(Decode)]
                            enum Node {
                                Node0,
                                Node1 {
                                    #[knuffel(argument)] a: i32,
                                    #[knuffel(argument)] b: String
                                },
                                Node2 {
                                    #[knuffel(property)] a: i32,
                                    #[knuffel(property)] b: String
                                }
                            }</pre>
    </td>
  </tr>
</table>

But when it comes to modelling children, knuffel supposes a different syntactical site to be those children's names:

```kdl
node {
  child 1
}
```

is modelled not by

```
#[derive(Decode)]
struct Node {
    #[knuffel(child)]
    a: Child
}

#[derive(Decode)]
struct Child(#[knuffel(argument)] i32);
```

but

```
#[derive(Decode)]
struct Node {
    #[knuffel(child)]
    child: A
}

#[derive(Decode)]
struct A(#[knuffel(argument)] i32);
```

And this is the cause of every problem in knuffel ––

- Impossibility

Since the child's name is anchored by the _field_'s name, enums with `Decode` cannot be used for the single child. #7

- Inconsistency

This especially comes up when combined with serde's `Serialize` derive macro and `knuffel::parse::<Vec<Node>>` pattern, where the `Node`'s aren't camel-cased (`node`) but outputted raw (`Node`).

- Redundancy

  - `children` directive takes `name` argument.
  - `node_name` attribute.
  - `type_name` attribute.

- Partiality

Tuple structs cannot have children, only struct structs can.

- Incompleteness

- Structural typing

Instead of nominal typing which must be the culmination in writing KDL and the shared spirit with Rust.

**Comment by tailhook** [comment]
Well, yes we use Rust attribute names for the names of childs. I think this leads to a better reusability.

And `node_name` and `type_name` attributes are needed to model more complex stuff, where custom node names can be used by user of the kdl file. I.e:
```
files {
  user_file1
  user_file2
}
```
In your model, `user_file1` and `user_file2` should be rust type names which doesn't make sense.

I don't think struct's inner type name can be used for matching:
1. Because it'll make more parser building at runtime (i.e we have to find out all children type names from fields first, because this is limitation of rust derives). So no compile-time checking of fields, which is a strong thing for knuffel.
2. It's unclear what to do with:
```
struct Document { a: Child, b: Child, c: Child }
```
I don't think "positional-named" childs make sense (i.e. every child matches by type name, and then also by position).

Generally knuffel allows you chosing one of the three node styles:
1. It's a "record". Where each child is a named property (use `child` with property names)
2. It's a bunch of nodes, each one of a set of types (use `children` with an enum as property type)
3. It's a dict where every node can be named differently (use `children` with property type of struct having `node_name` inside).

It also allows combining (1) and (2) or (3). Which is enough for config files. And for very special things it can be emulated by some of these methods and adding a postcheck.

I think this is generally flexible enough. Although, I understand that guide-level documentation is missing. So I appreciate contributions for the documentation.

**Comment by rnarkk** [comment]
I’m glad to know that you’ve come back! 🇺🇦

I have forked your knuffel and actually fixed nearly every problem and issues submitted to this project. I have made a considerable amount of changes both in its implementation and concepts, and each of them would be exciting and make sense for you, the original author, as well. So please check it out https://github.com/synthet-ic/kfl!

Some of the changes includes: 

- Make knuffel completely nominal-typing and trait-driven
- Implement Encode and its derive macro
- Make KDL scalar values more literal

——

As a reply only to this issue, the point was (as a hindsight from the huge refactoring) it’s not about positional but quantification of children, from only n to 0/1/n, like regex. And if you want to have multiple children of the same type, you must declare the name (=type) for those values first:

```kdl
files {
  file user_file1
  file user_file2
}
```

This is the idea of nominal-typing. Actually, as a hindsight again, `node_name` and `type_name` have different and necessary meanings in the AST: they are a variant name and an enum name when a node is defined by an enum.

**Comment by tailhook** [comment]
> Otherwise, the two (not three, four, .. but two) values must have distinct purposes in your configuration that deserve each different name (=type), for example, src and dest.

Right. And this is actually a feature :)

> Make knuffel completely nominal-typing and trait-driven

You mean for children only right? Because for scalars I don't see any difference.

> Implement Encode and its derive macro

Great!

> Make KDL scalar values more literal

Not sure what it means.

---

Overall on your examples I see the only difference, is that sometimes you need to put a name on the `children`:
```rust
#[derive(Decode)]
struct Document {
    #[kfl(children(name="route"))]
    routes: Vec<Route>,
    #[kfl(children(name="plugin"))]
    plugins: Vec<Plugin>,
}
```

Which is a good trade off. Because I remember sometimes I want reuse types, like in your example:
```rust
#[derive(Decode)]
struct Document {
    #[kfl(child)]
    src: FileSpec,
    #[kfl(children(name="plugin"))]
    dest: FileSpec,
}

#[derive(Decode)]
struct FileSpec {
    #[kfl(argument)]
    filename: PathBuf,
    #[kfl(property)]
    format: FileFormat,
}
```

**Comment by tailhook** [comment]
> I have made KDL file format transparent to Rust itself

Sorry, but I'm not sure what that means.

> Decode trait is now explicitly implemented for Option<T> and Vec<T>

Well, there are no arrays/lists/vectors in KDL, so what do you mean?

Regarding the option. I don't remember the details. But I probably could implement `Option<T>` where `x=null` means `None`, but absense of thing has to be processed by the macro itself.

I kinda understand that with enough trait magic that can be somehow solved, but I'm not sure if it's easy enough to make error handling on par when doing that.

> now we are free from quoting scalar values such as /path/to/file, 172.0.0.1:80, 2023-3-15 or http://example.com

I think you have to quote arguments and properties by KDL spec. You can non-quote node names, but I usually don't like node names that look complex. But example that looks nice to you might help to get your understanding clearer.

> if String is just another scalar value, what is 'literal' at this level?

Not sure what you mean. Literals in the AST are scalar values.

> Your idea of exposing ast::Node for crate users

This is basically exposing dynamically typed documents as part of statically typed document. I needed that for plugins (i.e. to embed configuration of the plugin that isn't known at compile-time). And I got this idea from the serde.
